# Generated by Django 4.2.16 on 2024-09-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandlisting',
            name='snippet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bandlisting',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
