# Generated by Django 4.2.16 on 2024-09-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band_listing', '0003_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandlisting',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
