# Generated by Django 4.2.16 on 2024-09-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_listing', '0005_alter_bandlisting_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandlisting',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
