# Generated by Django 4.2.16 on 2024-09-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_listing', '0006_alter_bandlisting_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandlisting',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
