# Generated by Django 4.2.16 on 2024-09-22 08:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band_listing', '0008_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandlisting',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='default-image.jpg', max_length=255, verbose_name='image'),
        ),
    ]
