# Generated by Django 4.2.16 on 2024-09-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_listing', '0009_alter_bandlisting_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandlisting',
            name='photo',
            field=models.ImageField(blank=True, default='images/default-image.jpg', upload_to='band_photos/'),
        ),
    ]
