# Generated by Django 4.2.16 on 2024-09-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_listing', '0010_alter_bandlisting_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandlisting',
            name='photo',
            field=models.ImageField(blank=True, default='default-image.jpg', null=True, upload_to='band_photos/'),
        ),
    ]
