# Generated by Django 4.2.16 on 2024-09-23 07:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band_listing', '0011_alter_bandlisting_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandlisting',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='images/default-image.jpg', max_length=255, null=True, verbose_name='photo'),
        ),
    ]
