# Generated by Django 4.2.16 on 2024-09-23 07:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band_listing', '0012_alter_bandlisting_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandlisting',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dzx1hyh89/image/upload/v1727076263/default-image_kfzhkf.jpg', max_length=255, null=True, verbose_name='photo'),
        ),
    ]
