# Generated by Django 4.2.16 on 2024-09-24 08:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_listing', '0013_alter_bandlisting_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bandlisting',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='default-image_kfzhkf.jpg', max_length=255, null=True, verbose_name='photo'),
        ),
    ]
